version: '3.7'
services:
  client:
    build: ./client
    stdin_open: true
    ports:
      - "3000:3000"
  server:
    build: ./go-server
    env_file:
      - go-server/.env
    ports: 
      - "9090:9090"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    environment: 
      MONGO_INITDB_DATABASE: database
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports: 
      - 27017:27017
    volumes: 
      - ./mongo:/data/db 
